# Travis CI build configuration for MediaWiki
# <https://travis-ci.org/wikimedia/mediawiki-core>
#
# The Wikimedia Foundation uses a self-hosted Jenkins instance to run unit
# tests, but it tests code against the version of PHP that is deployed on
# Wikimedia's production cluster. This Travis CI configuration is designed to
# complement that setup by testing MediaWiki on travis
#
language: php

php:
  - hhvm-nightly

env:
  - HHVM_ARGS="-c empty.ini"
  - HHVM_ARGS="--no-config"
  - HHVM_ARGS="--php"
  - HHVM_ARGS="-vEval.Jit=false"
  - HHVM_ARGS=""

before_install:
  - sudo apt-get install -qq sqlite3
before_script:
  - composer install --quiet --no-interaction
  - >
      php maintenance/install.php traviswiki admin
      --pass travis
      --dbtype sqlite
      --dbname traviswiki
      --dbuser travis
      --dbpath .
      --dbpass ""
      --scriptpath "/w"

script: ./.travis/run_tests.sh

notifications:
  email: false
